name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
      steps:
        - uses: actions/checkout@v2
        - name: my-step
        run: ci/build-app.sh
  Test:
    needs: Clone-down
      steps:
        - name: test
        run: ci/unit-test-app.sh
  Build:
    needs: Test
      steps:
        - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .