name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-Down
        uses: actions/checkout@v2
  Test:
    needs: Clone-Down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: ci/unit-test-app.sh
  Build:
    needs: Test
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
      - name: Upload a Build Artifact
        run: ci/build-app.sh